name: multi_vendor_cloud_resturent_system
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core (required)
  firebase_core: ^2.18.0

  # Firebase Authentication
  firebase_auth: ^4.11.1

  # Cloud Firestore
  cloud_firestore: ^4.15.1

  # Firebase Storage (if you'll handle images)
  firebase_storage: ^11.7.1

  # Provider for state management
  provider: ^6.1.1

  # Additional helpful packages
  image_picker: ^1.0.4       # For profile pictures
  # fluttertoast: ^8.2.8     # For toast messages
  charts_flutter: ^0.12.0    # For charts
  cached_network_image: ^3.3.0 # For image caching
  intl: ^0.17.0
  cupertino_icons: ^1.0.8
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
